version: '3.8'
services:

  redis_server:
    env_file:
      - .env
    image: redis:7.2.3-alpine3.18
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/var/lib/redis
    networks:
      - back_net
    entrypoint: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    restart: always

  flask_redis_editor:
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis_server
    depends_on:
      - redis_server
    build:
      context: flask_redis_editor/.
      dockerfile: Dockerfile
    networks:
      - back_net
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}                    # outside_port: docker_port (port forwarding)
    command: ["run", "--port", "${FLASK_PORT}", "--host=0.0.0.0"]
    restart: always

networks:
  back_net: {}
